-- Drive SoCal POV - Location Data Migration
-- Generated: 2025-10-16T22:58:51.404Z
-- Total Locations: 29

-- Begin transaction
BEGIN;

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('la-jolla-cove', 'La Jolla Cove', 'Picturesque cove beach with clear waters, sea lions, and stunning coastal views', 'La Jolla Cove is a small, picturesque cove and beach in La Jolla, San Diego. Known for its crystal-clear waters, abundant sea life, and dramatic coastal scenery. The area is perfect for swimming, snorkeling, and observing sea lions and seals in their natural habitat. The surrounding cliffs and coves offer excellent photo opportunities.', 'https://www.sandiego.gov/park-and-recreation/parks/beaches', '(858) 459-2555', '1100 Coast Blvd, La Jolla, CA 92037', 'San Diego', 'San Diego', '92037', ST_GeomFromText('SRID=4326;POINT(-117.2719 32.8509)'), true, 4.7, 8923, ARRAY['https://images.unsplash.com/photo-1579605071242-c6a66f5484d4?w=800'], ARRAY['beach', 'snorkeling', 'sea-lions', 'photography', 'family-friendly', 'swimming'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'picnic areas'], false, false, true, '{"beach":"24/7","parking":"Varies, typically 8:00-20:00"}'::jsonb, ARRAY['spring', 'summer', 'fall'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('mission-beach', 'Mission Beach', 'Vibrant 2-mile beach boardwalk with Belmont Park amusement park, surfing, and beach volleyball', 'Mission Beach is a lively 2-mile stretch of sand connecting San Diego Bay to the Pacific Ocean. The beach features a bustling boardwalk perfect for walking, biking, and skating, with Belmont Park amusement park featuring the historic Giant Dipper roller coaster. The area is popular for swimming, surfing, beach volleyball, and people-watching.', 'https://www.sandiego.gov/park-and-recreation/parks/mission-beach', 'Mission Beach, San Diego, CA 92109', 'San Diego', 'San Diego', '92109', ST_GeomFromText('SRID=4326;POINT(-117.2515 32.7725)'), true, 4.6, 8950, ARRAY['https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800'], ARRAY['boardwalk', 'surfing', 'beach-volleyball', 'family-friendly', 'amusement-park', 'biking', 'skating'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'restaurants', 'shops', 'rentals'], false, false, true, '{"beach":"24/7","boardwalk":"24/7","belmont_park":"11:00-20:00 (seasonal)"}'::jsonb, ARRAY['spring', 'summer', 'fall'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('pacific-beach', 'Pacific Beach', 'Energetic beach town atmosphere with surfing, beach bars, and vibrant nightlife', 'Pacific Beach is a youthful, energetic beach community known for its wide sandy beaches, excellent surfing conditions, and lively social scene. The area features a bustling boardfront with numerous bars, restaurants, and shops. PB attracts a younger crowd and is famous for its beach volleyball, surfing culture, and vibrant nightlife.', 'https://www.pacificbeach.org/', 'Pacific Beach, San Diego, CA 92109', 'San Diego', 'San Diego', '92109', ST_GeomFromText('SRID=4326;POINT(-117.2556 32.7958)'), true, 4.5, 10230, ARRAY['https://images.unsplash.com/photo-1579532582997-4b9c3c4a6a4b?w=800'], ARRAY['surfing', 'nightlife', 'beach-bars', 'young-crowd', 'volleyball', 'social-scene', 'boardfront'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'restaurants', 'bars', 'surf-shops'], false, false, true, '{"beach":"24/7","boardfront":"24/7","establishments":"Varies"}'::jsonb, ARRAY['spring', 'summer', 'fall'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('coronado-beach', 'Coronado Beach', 'Wide, sparkling sand beach with gentle waves and family-friendly atmosphere near Hotel del Coronado', 'Coronado Beach is renowned for its wide, sparkling golden sand and gentle waves, making it perfect for families and swimming. The beach stretches for miles with the iconic Hotel del Coronado as a backdrop. The flat terrain and calm waters make it ideal for children, while the expansive space accommodates beach volleyball, sunbathing, and long walks.', 'https://www.coronadovisitorcenter.com/beaches', 'Coronado Beach, Coronado, CA 92118', 'Coronado', 'San Diego', '92118', ST_GeomFromText('SRID=4326;POINT(-117.1832 32.6848)'), true, 4.8, 12450, ARRAY['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800'], ARRAY['family-friendly', 'gentle-waves', 'wide-sand', 'hotel-del-coronado', 'swimming', 'romantic', 'fire-pits'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'picnic areas', 'fire-pits', 'beach-wheelchairs'], false, false, true, '{"beach":"24/7","facilities":"6:00-22:00"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('ocean-beach', 'Ocean Beach', 'Laid-back beach town with dog-friendly areas, fishing pier, and vintage surf culture', 'Ocean Beach (OB) embodies Southern California''s relaxed beach culture with a bohemian, eclectic vibe. The beach features a long fishing pier, dog-friendly areas, and excellent surf breaks. The community is known for its vintage shops, casual restaurants, and friendly locals. OB offers both beach and bay access, with the Ocean Beach Pier being the longest concrete pier on the West Coast.', 'https://www.oboceanc.org/', 'Ocean Beach, San Diego, CA 92107', 'San Diego', 'San Diego', '92107', ST_GeomFromText('SRID=4326;POINT(-117.2528 32.7522)'), true, 4.6, 9870, ARRAY['https://images.unsplash.com/photo-1505142468610-359e7d316be0?w=800'], ARRAY['dog-friendly', 'fishing-pier', 'surfing', 'bohemian', 'laid-back', 'vintage-culture', 'bay-access'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'fishing-pier', 'dog-park', 'volleyball-courts'], false, false, true, '{"beach":"24/7","pier":"24/7","dog-beach":"24/7"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('imperial-beach', 'Imperial Beach', 'Southernmost California beach with wide sand, gentle surf, and annual sand castle competition', 'Imperial Beach is San Diego County''s southernmost beach, offering wide sandy shores and gentle waves perfect for families. The beach is known for its annual U.S. Open Sandcastle Competition and excellent bird watching opportunities at the nearby Tijuana Estuary. The area provides a more relaxed, less crowded alternative to northern San Diego beaches.', 'https://www.imperialbeach.gov/247/Pier-Beach', 'Imperial Beach, CA 91932', 'Imperial Beach', 'San Diego', '91932', ST_GeomFromText('SRID=4326;POINT(-117.1132 32.5836)'), true, 4.4, 5230, ARRAY['https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800'], ARRAY['family-friendly', 'bird-watching', 'sandcastle-competition', 'relaxed', 'southernmost-beach', 'fishing-pier'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'fishing-pier', 'picnic-areas', 'playground'], false, false, true, '{"beach":"24/7","pier":"24/7","park-facilities":"6:00-22:00"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('silver-strand-state-beach', 'Silver Strand State Beach', 'Scenic narrow peninsula with both ocean and bay beaches, camping, and water sports', 'Silver Strand State Beach offers the unique experience of both Pacific Ocean and San Diego Bay beaches on a narrow strip of land. The park features camping facilities, calm bay waters perfect for swimming and kayaking, and ocean waves ideal for surfing. The area connects Coronado to Imperial Beach and provides spectacular views of both the ocean and bay.', 'https://www.parks.ca.gov/silverstrand', '5000 Hwy 75, Coronado, CA 92118', 'Coronado', 'San Diego', '92118', ST_GeomFromText('SRID=4326;POINT(-117.1234 32.6478)'), true, 4.7, 6850, ARRAY['https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800'], ARRAY['camping', 'bay-beach', 'ocean-beach', 'water-sports', 'kayaking', 'swimming', 'bird-watching'], ARRAY['camping', 'parking', 'restrooms', 'showers', 'lifeguards', 'picnic-areas', 'boat-launch'], false, false, true, '{"park":"24/7","camping":"Check-in 15:00, Check-out 12:00","day-use":"8:00-sunset"}'::jsonb, ARRAY['spring', 'summer', 'fall'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('la-jolla-shores-park', 'La Jolla Shores Park', 'Family-friendly crescent beach with gentle waves, grassy park, and kayak rentals', 'La Jolla Shores is a wide, crescent-shaped beach with gentle waves perfect for families and swimming. The adjacent park offers grassy areas, picnic tables, and playground equipment. The beach is popular for kayaking, stand-up paddleboarding, and scuba diving at the nearby La Jolla Ecological Reserve. Marine life viewing, including sea lions and dolphins, is common.', 'https://www.sandiego.gov/park-and-recreation/parks/lajolla-shores', '8300 Camino del Oro, La Jolla, CA 92037', 'San Diego', 'San Diego', '92037', ST_GeomFromText('SRID=4326;POINT(-117.2734 32.847)'), true, 4.7, 7890, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['family-friendly', 'kayaking', 'scuba-diving', 'marine-life', 'gentle-waves', 'picnicking', 'playground'], ARRAY['parking', 'restrooms', 'showers', 'lifeguards', 'playground', 'picnic-areas', 'grass-park', 'rentals'], false, false, true, '{"beach":"24/7","park":"24/7","facilities":"6:00-22:00"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'beaches');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('balboa-park', 'Balboa Park', 'Historic 1,200-acre urban cultural park with museums, gardens, and the San Diego Zoo', 'Balboa Park is a 1,200-acre historic urban cultural park in San Diego, California. The park contains numerous museums, theaters, gardens, shops, restaurants, and the world-famous San Diego Zoo. Many of the park''s attractions are free to explore, including beautiful gardens, walking paths, and architectural landmarks.', 'https://www.balboapark.org/', '1549 El Prado, San Diego, CA 92101', 'San Diego', 'San Diego', '92101', ST_GeomFromText('SRID=4326;POINT(-117.1596 32.7341)'), true, 4.8, 15420, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['family-friendly', 'outdoors', 'museums', 'gardens', 'historic', 'cultural'], ARRAY['parking', 'restrooms', 'gift shops', 'restaurants', 'museums'], false, false, true, '{"park":"24/7","museums":"Varies by location"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('torrey-pines-state-natural-reserve', 'Torrey Pines State Natural Reserve', '2,000-acre coastal wilderness reserve with rare Torrey pine trees, hiking trails, and dramatic cliff views', 'Torrey Pines State Natural Reserve is one of the wildest stretches of land on the Southern California coast, featuring rare Torrey pine trees, miles of unspoiled beaches, and stunning ocean cliffs. The reserve offers numerous hiking trails with breathtaking views of the Pacific Ocean, making it a paradise for nature lovers and hikers.', 'https://www.parks.ca.gov/torreypines', '(858) 755-2063', '12600 N Torrey Pines Rd, La Jolla, CA 92037', 'San Diego', 'San Diego', '12600', ST_GeomFromText('SRID=4326;POINT(-117.2532 32.9218)'), true, 4.9, 8750, ARRAY['https://images.unsplash.com/photo-1508672019048-805c876b67e2?w=800'], ARRAY['hiking', 'nature', 'wildlife', 'cliffs', 'beaches', 'photography', 'rare-trees'], ARRAY['parking', 'restrooms', 'visitor center', 'hiking trails', 'beach access'], false, false, true, '{"reserve":"Sunrise to sunset","visitor_center":"9:00-18:00"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('sunset-cliffs-natural-park', 'Sunset Cliffs Natural Park', '68-acre coastal park with dramatic sunset views, rugged cliffs, and ocean vistas', 'Sunset Cliffs Natural Park offers spectacular sunset views over the Pacific Ocean with dramatic coastal cliffs and sea caves. The park features walking paths, scenic viewpoints, and natural rock formations. It''s one of San Diego''s most photographed locations, especially during golden hour when the cliffs glow with sunset colors.', 'https://www.sandiego.gov/park-and-recreation/parks/sunset-cliffs', '(619) 221-8899', '1253 Sunset Cliffs Blvd, San Diego, CA 92107', 'San Diego', 'San Diego', '92107', ST_GeomFromText('SRID=4326;POINT(-117.2512 32.7514)'), true, 4.7, 6820, ARRAY['https://images.unsplash.com/photo-1578873292081-1f8b5b5f1e6e?w=800'], ARRAY['sunset', 'cliffs', 'ocean-views', 'photography', 'romantic', 'natural-beauty'], ARRAY['parking', 'walking paths', 'scenic viewpoints'], false, false, true, '{"park":"24/7","best_viewing":"1 hour before sunset"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('old-town-san-diego-state-historic-park', 'Old Town San Diego State Historic Park', 'Historic park recreating San Diego life in the 1820s with original adobe buildings and period demonstrations', 'Old Town San Diego State Historic Park preserves and recreates San Diego''s early Mexican and American period. The park features historic adobe buildings, museums, restaurants, and shops. Visitors can enjoy free walking tours, watch blacksmith demonstrations, and experience California''s early history. The park comes alive with colorful fiestas and cultural events throughout the year.', 'https://www.parks.ca.gov/oldtownsandiego', '(619) 220-5422', '4002 Wallace St, San Diego, CA 92110', 'San Diego', 'San Diego', '92110', ST_GeomFromText('SRID=4326;POINT(-117.1968 32.7543)'), true, 4.6, 12450, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['history', 'mexican-heritage', 'museums', 'culture', 'family-friendly', 'shopping', 'restaurants'], ARRAY['parking', 'restrooms', 'gift shops', 'restaurants', 'museums', 'walking tours'], false, false, true, '{"park":"24/7","buildings":"10:00-17:00","restaurants":"Varies"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('seaport-village', 'Seaport Village', 'Waterfront shopping and dining area with street performers, art galleries, and harbor views', 'Seaport Village is a 14-acre waterfront shopping, dining, and entertainment complex along San Diego Bay. While shopping and dining cost money, visitors can enjoy free strolling along the waterfront, watch street performers, browse window displays, and enjoy beautiful harbor views. The area features historic ships, art installations, and regular free events.', 'https://www.seaportvillage.com/', '(619) 235-4014', '849 W Harbor Dr, San Diego, CA 92101', 'San Diego', 'San Diego', '92101', ST_GeomFromText('SRID=4326;POINT(-117.1758 32.7144)'), true, 4.4, 9320, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['waterfront', 'shopping', 'dining', 'entertainment', 'street-performers', 'harbor-views', 'family-friendly'], ARRAY['parking', 'restrooms', 'waterfront access', 'public art'], false, false, true, '{"area":"24/7","shops":"10:00-20:00 (varies by store)","restaurants":"Varies"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'shopping');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('gaslamp-quarter', 'Gaslamp Quarter', 'Historic Victorian-era district with 16 blocks of dining, shopping, and entertainment venues', 'The Gaslamp Quarter is a 16-block historic neighborhood in downtown San Diego, known for its Victorian architecture, vibrant nightlife, and diverse dining scene. While restaurants and clubs charge admission, the area is free to explore on foot. Visitors can admire the historic architecture, enjoy street performances, and soak in the lively atmosphere of this National Historic District.', 'https://www.gaslamp.org/', '(619) 233-5227', '5th Ave & Island Ave, San Diego, CA 92101', 'San Diego', 'San Diego', '92101', ST_GeomFromText('SRID=4326;POINT(-117.1619 32.7105)'), true, 4.5, 7850, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['historic', 'architecture', 'nightlife', 'dining', 'shopping', 'entertainment', 'victorian'], ARRAY['parking', 'restrooms', 'historic-architecture', 'street-performers'], false, false, true, '{"area":"24/7","businesses":"Varies by establishment"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "phone", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('mission-bay-park', 'Mission Bay Park', '4,600-acre aquatic park with beaches, bike paths, and water sports activities', 'Mission Bay Park is a massive 4,600-acre aquatic park offering 27 miles of shoreline, including numerous beaches, picnic areas, and recreational facilities. The park is perfect for biking, walking, jogging, and water sports. Visitors can enjoy free beach access, playgrounds, and beautiful bay views. The calm waters make it ideal for families and water sports enthusiasts.', 'https://www.sandiego.gov/park-and-recreation/parks/mission-bay', '(619) 694-3049', '2688 E Mission Bay Dr, San Diego, CA 92109', 'San Diego', 'San Diego', '92109', ST_GeomFromText('SRID=4326;POINT(-117.2134 32.7795)'), true, 4.6, 5890, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['beaches', 'water-sports', 'biking', 'picnicking', 'family-friendly', 'recreation', 'bay-views'], ARRAY['parking', 'restrooms', 'playgrounds', 'beach access', 'bike paths', 'picnic areas'], false, false, true, '{"park":"24/7","facilities":"Varies by location"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "price_level", "is_free", "cost_estimate", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('san-diego-zoo', 'San Diego Zoo', 'World-famous zoo with 12,000 animals in naturalistic habitats, conservation leader', 'The San Diego Zoo is a world-renowned zoo housing over 12,000 animals of more than 650 species and subspecies. Known for its pioneering approach to naturalistic animal enclosures and conservation efforts, the zoo offers guided tours, special experiences, and educational programs. It''s one of the few zoos in the world to house giant pandas and is internationally recognized for its breeding programs.', 'https://zoo.sandiegozoo.org/', '2920 Zoo Dr, San Diego, CA 92101', 'San Diego', 'San Diego', '92101', ST_GeomFromText('SRID=4326;POINT(-117.149 32.7353)'), 4, false, 'Adults: $62-75, Children: $52-65, Seniors: $52-65', 4.8, 45890, ARRAY['https://images.unsplash.com/photo-1583337134317-4bf93c5fee04?w=800'], ARRAY['animals', 'conservation', 'family-friendly', 'pandas', 'world-class', 'educational'], ARRAY['parking', 'restrooms', 'restaurants', 'gift shops', 'transportation', 'guided-tours'], true, false, true, '{"zoo":"9:00-18:00 (daily, hours vary by season)","special_experiences":"Varies by program"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('griffith-park', 'Griffith Park', '4,210-acre urban park with hiking trails, Griffith Observatory, and Hollywood Sign views', 'Griffith Park is one of the largest urban parks in North America, offering extensive hiking trails, picnic areas, and stunning views of Los Angeles and the iconic Hollywood Sign. While the Griffith Observatory and planetarium shows require tickets, the park grounds, hiking trails, and many viewpoints are completely free to explore.', 'https://www.laparks.org/griffithpark', '4730 Crystal Springs Dr, Los Angeles, CA 90027', 'Los Angeles', 'Los Angeles', '90027', ST_GeomFromText('SRID=4326;POINT(-118.2935 34.1365)'), true, 4.8, 25680, ARRAY['https://images.unsplash.com/photo-1520467790875-79e45456c6c0?w=800'], ARRAY['hiking', 'hollywood-sign', 'city-views', 'family-friendly', 'outdoors', 'picnicking', 'nature'], ARRAY['parking', 'restrooms', 'hiking trails', 'picnic areas', 'playgrounds', 'horseback riding'], false, false, true, '{"park":"24/7","observatory_exterior":"24/7","facilities":"Varies by location"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('the-getty-center', 'The Getty Center', 'World-class art museum with stunning architecture, gardens, and panoramic city views', 'The Getty Center is a world-renowned art museum featuring European paintings, drawings, sculptures, decorative arts, and photographs from the Middle Ages to the present. The complex is famous for its stunning architecture, beautiful gardens, and panoramic views of Los Angeles. While parking costs money, admission to the museum and all exhibitions is completely free.', 'https://www.getty.edu/visit/center/', '1200 Getty Center Dr, Los Angeles, CA 90049', 'Los Angeles', 'Los Angeles', '90049', ST_GeomFromText('SRID=4326;POINT(-118.4747 34.0775)'), true, 4.7, 18950, ARRAY['https://images.unsplash.com/photo-1594736797933-d0acc2401915?w=800'], ARRAY['art', 'architecture', 'gardens', 'city-views', 'family-friendly', 'photography', 'culture'], ARRAY['parking', 'restrooms', 'restaurants', 'gift shops', 'gardens', 'audio-guides'], false, false, true, '{"museum":"Tuesday-Friday: 10:00-17:00, Saturday-Sunday: 10:00-17:00","gardens":"24/7 access","closed":"Mondays"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'culture-and-arts');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('hollywood-walk-of-fame', 'Hollywood Walk of Fame', 'Iconic sidewalk with celebrity stars, historic theaters, and Hollywood glamour', 'The Hollywood Walk of Fame is a world-famous attraction featuring more than 2,600 brass stars embedded in the sidewalks along Hollywood Boulevard and Vine Street. The walk celebrates achievements in the entertainment industry, with stars honoring actors, musicians, directors, and other celebrities. The surrounding area includes historic theaters like the TCL Chinese Theatre and the Dolby Theatre.', 'https://www.walkoffame.com/', 'Hollywood Blvd & Vine St, Los Angeles, CA 90028', 'Los Angeles', 'Los Angeles', '90028', ST_GeomFromText('SRID=4326;POINT(-118.3269 34.1018)'), true, 4.4, 32480, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['hollywood', 'celebrities', 'entertainment', 'historic-theaters', 'photography', 'tourist-attraction'], ARRAY['parking', 'restrooms', 'restaurants', 'shops', 'tourist-information'], false, false, true, '{"walk":"24/7","ceremonies":"Varies by event","theaters":"Varies by venue"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('santa-monica-pier', 'Santa Monica Pier', 'Historic pier with carnival rides, Pacific Park amusement area, and beachfront views', 'The Santa Monica Pier is a historic landmark dating back to 1909, featuring the Pacific Park amusement area with rides like the solar-powered Pacific Wheel Ferris wheel and West Coaster roller coaster. While individual rides cost money, walking on the pier, enjoying ocean views, and watching the sunset are completely free. The pier offers classic beach town atmosphere with street performers, fishing, and dining options.', 'https://www.santamonicapier.org/', '200 Santa Monica Pier, Santa Monica, CA 90401', 'Santa Monica', 'Los Angeles', '90401', ST_GeomFromText('SRID=4326;POINT(-118.4998 34.0089)'), true, 4.5, 19458, ARRAY['https://images.unsplash.com/photo-1505228395891-9a51e7e86bf6?w=800'], ARRAY['beach', 'pier', 'amusement-rides', 'sunset', 'family-friendly', 'ocean-views', 'historic'], ARRAY['parking', 'restrooms', 'restaurants', 'shops', 'fishing', 'playground'], false, false, true, '{"pier":"24/7","rides":"Monday-Friday: 12:00-20:00, Saturday-Sunday: 11:00-20:00","seasonal_hours":"Extended summer hours"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'outdoor-activities');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('venice-beach-boardwalk', 'Venice Beach Boardwalk', 'Eclectic boardwalk with street performers, artists, skate park, and Venice Canals', 'The Venice Beach Boardwalk is one of LA''s most iconic and colorful destinations, featuring a diverse array of street performers, artists, vendors, and attractions. The area includes the famous Venice Skate Park, outdoor basketball courts, bodybuilding areas, and numerous shops and cafes. The adjacent Venice Canals offer a peaceful contrast with beautiful residential waterways. It''s a celebration of LA''s bohemian beach culture.', 'https://www.laparks.org/venice/', '1800 Ocean Front Walk, Los Angeles, CA 90291', 'Los Angeles', 'Los Angeles', '90291', ST_GeomFromText('SRID=4326;POINT(-118.4695 33.985)'), true, 4.6, 21890, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['street-performers', 'skateboarding', 'beach-culture', 'bohemian', 'artists', 'canals', 'basketball'], ARRAY['parking', 'restrooms', 'skate-park', 'basketball-courts', 'outdoor-gym', 'shops'], false, false, true, '{"boardwalk":"24/7","facilities":"Varies by location","skate_park":"8:00-sunset"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions', 'outdoor-activities');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('runyon-canyon-park', 'Runyon Canyon Park', 'Popular hiking trail with Hollywood Sign views and celebrity sightings', 'Runyon Canyon Park is one of LA''s most famous hiking spots, offering scenic trails with panoramic views of Los Angeles and the Hollywood Sign. The park attracts fitness enthusiasts, dog walkers, and celebrities seeking exercise. Multiple trail options range from easy walks to challenging hikes, making it accessible to various fitness levels. The park is known for its social scene and stunning city views.', 'https://www.laparks.org/runyon-canyon-park', '2000 N Fuller Ave, Los Angeles, CA 90046', 'Los Angeles', 'Los Angeles', '90046', ST_GeomFromText('SRID=4326;POINT(-118.3448 34.1269)'), true, 4.4, 8750, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['hiking', 'city-views', 'hollywood-sign', 'dog-friendly', 'fitness', 'celebrity-sightings'], ARRAY['parking', 'hiking trails', 'water fountains', 'bag dispensers', 'multiple entrances'], false, false, true, '{"park":"24/7","gates":"6:30-dusk","best_hiking":"Early morning or late afternoon"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('olvera-street', 'Olvera Street', 'Birthplace of Los Angeles with historic Mexican marketplace and cultural attractions', 'Olvera Street is known as the birthplace of Los Angeles, offering a vibrant taste of old Mexico with historic buildings, traditional restaurants, and colorful shops. The street features the Avila Adobe, the oldest standing residence in Los Angeles, along with museums, cultural performances, and authentic Mexican cuisine. It''s a free outdoor museum celebrating LA''s Mexican heritage and founding.', 'https://olvera-street.com/', '845 N Alameda St, Los Angeles, CA 90012', 'Los Angeles', 'Los Angeles', '90012', ST_GeomFromText('SRID=4326;POINT(-118.2369 34.0626)'), true, 4.4, 6580, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['history', 'mexican-heritage', 'culture', 'museums', 'shopping', 'traditional-food', 'founding-of-LA'], ARRAY['parking', 'restrooms', 'museums', 'restaurants', 'shops', 'cultural-performances'], false, false, true, '{"street":"10:00-19:00 (daily)","museums":"10:00-16:00 (Wednesday-Sunday)","restaurants":"Varies by establishment"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('the-grove', 'The Grove', 'Outdoor shopping center with beautiful landscaping, fountain shows, and free trolley', 'The Grove is an upscale outdoor shopping and entertainment center featuring beautiful architecture, landscaping, and a choreographed fountain show. While shopping and dining cost money, visitors can enjoy free strolling through the property, watching the fountain shows, riding the free trolley to The Original Farmers Market, and admiring the ambiance. The center features a dancing water fountain synchronized to music and seasonal decorations.', 'https://www.thegrovela.com/', '189 The Grove Dr, Los Angeles, CA 90036', 'Los Angeles', 'Los Angeles', '90036', ST_GeomFromText('SRID=4326;POINT(-118.357 34.0481)'), true, 4.6, 12450, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['shopping', 'outdoor-mall', 'fountain-shows', 'family-friendly', 'dining', 'entertainment'], ARRAY['parking', 'restrooms', 'free-trolley', 'fountain-shows', 'playground'], false, false, true, '{"center":"10:00-21:00 (Monday-Saturday), 11:00-19:00 (Sunday)","fountain_shows":"Every hour during operating hours","trolley":"During center hours"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'shopping', 'shopping');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('mission-inn-festival-of-lights', 'Mission Inn Festival of Lights', 'Historic hotel with spectacular Christmas light display and holiday festivities', 'The Mission Inn Festival of Lights is a spectacular holiday tradition featuring over 5 million lights decorating the historic Mission Inn Hotel. While the hotel itself requires paid access, the outdoor light display and surrounding festivities are completely free to enjoy from the street. The event includes live entertainment, holiday vendors, and beautiful holiday decorations throughout downtown Riverside.', 'https://www.missioninn.com/festival-of-lights', '3649 Mission Inn Ave, Riverside, CA 92501', 'Riverside', 'Inland Empire', '92501', ST_GeomFromText('SRID=4326;POINT(-117.3769 33.9832)'), true, 4.8, 12480, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['holiday', 'christmas', 'lights', 'historic-hotel', 'family-tradition', 'festivals'], ARRAY['parking', 'restaurants', 'shopping', 'entertainment', 'historic-architecture'], false, false, true, '{"light_display":"Daily from late November through December, 17:00-24:00","seasonal":"Holiday season only (November-January)"}'::jsonb, ARRAY['winter'], 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('march-field-air-museum', 'March Field Air Museum', 'Aviation museum with historic aircraft and free outdoor aircraft displays', 'March Field Air Museum features an impressive collection of historic aircraft and aviation artifacts, with many aircraft displayed outdoors for free viewing. The indoor museum has an admission fee, but the outdoor aircraft collection, including helicopters, fighter jets, and bombers from various eras, can be viewed completely free. The museum is located at the historic March Air Reserve Base.', 'https://www.marchfield.org/', '22550 Van Buren Blvd, Riverside, CA 92518', 'Riverside', 'Inland Empire', '22550', ST_GeomFromText('SRID=4326;POINT(-117.4256 33.8769)'), true, 4.6, 6890, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['aviation', 'military', 'aircraft', 'history', 'family-friendly', 'outdoor-exhibits'], ARRAY['parking', 'gift shop', 'restrooms', 'picnic areas'], false, false, true, '{"outdoor_displays":"24/7 visibility from perimeter","museum":"10:00-17:00 (Tuesday-Sunday, paid admission)","closed":"Mondays"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'attractions');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug", "subcategory_slug") VALUES ('pioneer-park', 'Pioneer Park', 'Historic park with original Temecula buildings, museums, and Old West charm', 'Pioneer Park in Temecula preserves the town''s pioneer heritage with historic buildings, including the original Temecula jail, schoolhouse, and various pioneer-era structures. The park offers free outdoor exploration of historic buildings, picnic areas, and beautiful views of the surrounding countryside. It''s a peaceful step back into Southern California''s Old West history.', 'https://www.temeculaca.gov/ThingsToDo/PioneerPark', '31985 Moreno Rd, Temecula, CA 92592', 'Temecula', 'Inland Empire', '31985', ST_GeomFromText('SRID=4326;POINT(-117.1474 33.4968)'), true, 4.5, 3240, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['history', 'pioneer-era', 'old-west', 'picnicking', 'family-friendly', 'historic-buildings'], ARRAY['parking', 'restrooms', 'picnic areas', 'walking paths', 'historic-structures'], false, false, true, '{"park":"24/7","building_viewing":"Outdoor viewing available anytime","picnic_areas":"24/7"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks', 'parks-and-recreation');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('big-bear-discovery-center', 'Big Bear Discovery Center', 'Mountain nature center with forest information, trails, and wildlife education', 'The Big Bear Discovery Center serves as the gateway to the San Bernardino National Forest, offering free outdoor exhibits, trail information, and educational displays about local wildlife and forest ecology. While some programs and facility rentals have fees, the center itself, outdoor exhibits, and access to trail heads are completely free. It''s an excellent starting point for exploring Big Bear Lake''s natural beauty.', 'https://www.disbigbear.com/', '40971 North Shore Dr, Fawnskin, CA 92333', 'Fawnskin', 'Inland Empire', '40971', ST_GeomFromText('SRID=4326;POINT(-116.8983 34.2712)'), true, 4.4, 4580, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['nature', 'wildlife', 'hiking', 'forests', 'mountains', 'family-friendly', 'education'], ARRAY['parking', 'restrooms', 'information center', 'trail access', 'picnic areas'], false, false, true, '{"center":"8:00-17:00 (daily)","outdoor_exhibits":"24/7 access","trails":"Dawn to dusk"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks');
-- Source: unknown/unknown

INSERT INTO locations ("slug", "name", "summary", "description", "website", "address", "city", "region", "postal_code", "coordinates", "is_free", "rating", "review_count", "photos", "tags", "amenities", "is_premium", "is_featured", "is_published", "hours", "seasonality", "category_slug") VALUES ('lake-perris-state-recreation-area', 'Lake Perris State Recreation Area', 'Large reservoir with beaches, hiking trails, fishing, and outdoor recreation', 'Lake Perris State Recreation Area offers diverse outdoor activities around a large reservoir in the heart of the Inland Empire. While day-use parking has fees, the lake perimeter can be accessed for free viewing from certain areas, and the surrounding hills provide excellent hiking opportunities. The park features sandy beaches, fishing areas, picnic spots, and beautiful mountain views.', 'https://www.parks.ca.gov/?page_id=656', '18700 Lake Perris Dr, Perris, CA 92571', 'Perris', 'Inland Empire', '18700', ST_GeomFromText('SRID=4326;POINT(-117.2479 33.7901)'), true, 4.5, 7890, ARRAY['https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=800'], ARRAY['lake', 'fishing', 'hiking', 'picnicking', 'beaches', 'outdoor-recreation', 'water-sports'], ARRAY['parking', 'restrooms', 'picnic areas', 'hiking trails', 'beach access', 'fishing'], false, false, true, '{"park":"24/7 access to perimeter areas","facilities":"Varies by season and facility type","day_use":"Sunrise to sunset"}'::jsonb, ARRAY['spring', 'summer', 'fall', 'winter'], 'parks');
-- Source: unknown/unknown


-- Update statistics
UPDATE locations SET
  data_completeness_score = CASE
    WHEN (website IS NOT NULL AND phone IS NOT NULL AND photos IS NOT NULL AND array_length(photos, 1) > 0) THEN 90
    WHEN (website IS NOT NULL OR phone IS NOT NULL) THEN 70
    ELSE 50
  END,
  content_quality_score = CASE
    WHEN (description IS NOT NULL AND length(description) > 200) THEN 85
    WHEN (description IS NOT NULL AND length(description) > 100) THEN 70
    WHEN (description IS NOT NULL) THEN 50
    ELSE 25
  END,
  search_score = CASE
    WHEN (rating >= 4.5 AND review_count > 1000) THEN 90
    WHEN (rating >= 4.0 AND review_count > 500) THEN 75
    WHEN (rating >= 3.5 AND review_count > 100) THEN 60
    WHEN (rating > 0) THEN 40
    ELSE 20
  END;

-- Commit transaction
COMMIT;

-- Migration Summary
-- Total: 29
-- Imported: 29
-- Errors: 0
-- Skipped: 0
